import type { IPet } from '../models/common.js'

export const mockPetData: IPet[] = [
  {
    slug: 'apricot',
    name: 'Apricot',
    physicalTraits: {
      species: 'Cat',
      breed: 'Domestic Short Hair',
      sex: 'Female',
      age: '2 years',
      size: 'Small',
      color: 'Cream',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: true,
      energyLevel: 'Medium',
      temperament: 'Affectionate',
      houseTrained: true,
    },
    medicalHistory: {
      vaccinationsUpToDate: true,
      spayedOrNeutered: true,
      microchipped: true,
    },
    adoptionFee: 75,
    descriptions: {
      medicalDescription: 'No known medical issues.',
      physicalDescription: 'Curious guy; professional treat inspector.',
      spotlightDescription: 'Montclair is our featured cat of the week — playful and cuddly!',
      behavioralDescription:
        'Loves interactive play and exploring. He thrives on puzzle toys and will keep you entertained with his antics.',
      aboutDescription:
        "Hi, I'm Montclair! I'm just a little kitten with a big heart, ready to bring joy and laughter into your life. I love to play with my toys, cuddle up in warm laps, and make new friends. My gentle nature makes me the perfect companion for cozy evenings and playful afternoons. If you're looking for a sweet, friendly, and loving friend, I'm your perfect match! Let's create unforgettable memories together. Adopt me and let's start our adventure!",
    },
    spotlight: true,
    spotlightDescription: 'Apricot is our featured cat of the week — playful and cuddly!',
    photos: ['/images/apricot-1.jpg', '/images/apricot-2.jpg'],
  },
]

export const mockPetsData: IPet[] = [
  {
    slug: 'apricot',
    name: 'Apricot',
    physicalTraits: {
      species: 'Cat',
      breed: 'Domestic Short Hair',
      sex: 'Female',
      age: '2 years',
      size: 'Small',
      color: 'Cream',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: true,
      energyLevel: 'Medium',
      temperament: 'Affectionate',
      houseTrained: true,
    },
    medicalHistory: {
      vaccinationsUpToDate: true,
      spayedOrNeutered: true,
      microchipped: true,
    },
    adoptionFee: 75,
    spotlight: true,
    descriptions: {
      medicalDescription: 'No known medical issues.',
      physicalDescription: 'Sweet, chatty lap buddy who loves feather wands.',
      spotlightDescription: 'Apricot is our featured cat of the week — playful and cuddly!',
      behavioralDescription:
        'Very social and loves human attention. She enjoys curling up in quiet spaces and thrives in calm households.',
      aboutDescription:
        "Hi, I'm Montclair! I'm just a little kitten with a big heart, ready to bring joy and laughter into your life. I love to play with my toys, cuddle up in warm laps, and make new friends. My gentle nature makes me the perfect companion for cozy evenings and playful afternoons. If you're looking for a sweet, friendly, and loving friend, I'm your perfect match! Let's create unforgettable memories together. Adopt me and let's start our adventure!",
      funDescription:
        'Loves chasing laser pointers and napping in sunny spots. She also enjoys climbing cat trees and observing the world from high perches. Her playful antics with feather toys will keep you entertained for hours. When she’s not playing, she loves curling up in a sunny spot for a nap.',
    },

    photos: ['/images/apricot-1.jpg', '/images/apricot-2.jpg'],
  },
  {
    slug: 'montclair',
    name: 'Montclair',
    physicalTraits: {
      species: 'Cat',
      breed: 'Domestic Short Hair',
      sex: 'Male',
      age: '3 years',
      size: 'Medium',
      color: 'Gray tabby',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: true,
      energyLevel: 'High',
      temperament: 'Playful',
      houseTrained: true,
    },
    medicalHistory: {
      vaccinationsUpToDate: true,
      spayedOrNeutered: true,
      microchipped: true,
      shots: {
        felineHerpesVirus: {
          description: 'Feline HerpesVirus-1',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        felineCalicivirus: {
          description: 'Feline Calicivirus',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        felinePanleukopenia1: {
          description: 'Feline Panleukopenia (FVRCP) 1 of 3',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        felinePanleukopenia2: {
          description: 'Feline Panleukopenia (FVRCP) 2 of 3',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        felinePanleukopenia3: {
          description: 'Feline Panleukopenia (FVRCP) 3 of 3',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        felineLeukemina1: {
          description: 'Feline Leukemina (FeLV) 1 of 2',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        felineLeukemina2: {
          description: 'Feline Leukemina (FeLV) 2 of 2',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        rabies: {
          description: 'Rabies',
          dateAdministered: '2023-01-15',
          receivedTreatment: true,
        },
        spayNeuter: {
          description: 'Spay/Neutered',
          dateAdministered: '2023-02-01',
          receivedTreatment: true,
        },
      },
    },
    adoptionFee: 300,
    spotlight: true,
    descriptions: {
      medicalDescription: 'No known medical issues.',
      physicalDescription: 'Curious guy; professional treat inspector.',
      spotlightDescription: 'Montclair is our featured cat of the week — playful and cuddly!',
      funDescription:
        "Hi, I'm Montclair! I'm just a little kitten with a big heart, ready to bring joy and laughter into your life. I love to play with my toys, cuddle up in warm laps, and make new friends. My gentle nature makes me the perfect companion for cozy evenings and playful afternoons. If you're looking for a sweet, friendly, and loving friend, I'm your perfect match! Let's create unforgettable memories together. Adopt me and let's start our adventure!",
      behavioralDescription:
        'Loves interactive play and exploring. He thrives on puzzle toys and will keep you entertained with his antics.',
      aboutDescription:
        "Hi, I'm Montclair! I'm just a little kitten with a big heart, ready to bring joy and laughter into your life. I love to play with my toys, cuddle up in warm laps, and make new friends. My gentle nature makes me the perfect companion for cozy evenings and playful afternoons. If you're looking for a sweet, friendly, and loving friend, I'm your perfect match! Let's create unforgettable memories together. Adopt me and let's start our adventure!",
    },
    photos: ['/images/montclair-1.jpg'],
  },
  {
    slug: 'crystal',
    name: 'Crystal',
    physicalTraits: {
      species: 'Cat',
      breed: 'Domestic Short Hair',
      sex: 'Female',
      age: '4 years',
      size: 'Small',
      color: 'White & gray',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: true,
      energyLevel: 'Low',
      temperament: 'Calm',
      houseTrained: true,
    },
    medicalHistory: {
      vaccinationsUpToDate: true,
      spayedOrNeutered: true,
      microchipped: false,
    },
    adoptionFee: 50,
    photos: ['/images/crystal-1.jpg'],
  },
  {
    slug: 'casper',
    name: 'Casper',
    physicalTraits: {
      species: 'Cat',
      breed: 'Domestic Short Hair',
      sex: 'Male',
      age: '1 year',
      size: 'Small',
      color: 'White',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: true,
      energyLevel: 'High',
      temperament: 'Sociable',
      houseTrained: true,
    },
    medicalHistory: {
      vaccinationsUpToDate: true,
      spayedOrNeutered: false,
      microchipped: true,
    },
    adoptionFee: 85,
    photos: ['/images/casper-1.jpg', '/images/casper-2.jpg'],
  },
  {
    slug: 'buddy',
    name: 'Buddy',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Male',
      age: '3 years',
      size: 'Medium',
      color: 'Brown',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: false,
      energyLevel: 'Medium',
      temperament: 'Friendly',
      houseTrained: true,
    },
    medicalHistory: { vaccinationsUpToDate: true, spayedOrNeutered: true, microchipped: true },
    adoptionFee: 150,
    descriptions: {
      medicalDescription: 'No known medical issues.',
      physicalDescription: 'Curious guy; professional treat inspector.',
      spotlightDescription: 'Montclair is our featured cat of the week — playful and cuddly!',
      behavioralDescription:
        'Loves interactive play and exploring. He thrives on puzzle toys and will keep you entertained with his antics.',
      aboutDescription:
        "Hi, I'm Montclair! I'm just a little kitten with a big heart, ready to bring joy and laughter into your life. I love to play with my toys, cuddle up in warm laps, and make new friends. My gentle nature makes me the perfect companion for cozy evenings and playful afternoons. If you're looking for a sweet, friendly, and loving friend, I'm your perfect match! Let's create unforgettable memories together. Adopt me and let's start our adventure!",
    },
    photos: ['/images/buddy-1.jpg'],
  },
  {
    slug: 'max',
    name: 'Max',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Male',
      age: '5 years',
      size: 'Large',
      color: 'Black',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: false,
      goodWithCats: false,
      energyLevel: 'Low',
      temperament: 'Laid-back',
      houseTrained: true,
    },
    medicalHistory: {
      vaccinationsUpToDate: true,
      spayedOrNeutered: true,
      microchipped: true,
    },
    adoptionFee: 120,
    photos: ['/images/max-1.jpg'],
  },
  {
    slug: 'bella',
    name: 'Bella',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Female',
      age: '2 years',
      size: 'Medium',
      color: 'Brown & white',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: true,
      energyLevel: 'High',
      temperament: 'Energetic',
      houseTrained: true,
    },
    medicalHistory: { vaccinationsUpToDate: true, spayedOrNeutered: false, microchipped: false },
    adoptionFee: 140,
    descriptions: {
      medicalDescription: 'No known medical issues.',
      physicalDescription: 'Curious guy; professional treat inspector.',
      spotlightDescription: 'Montclair is our featured cat of the week — playful and cuddly!',
      behavioralDescription:
        'Loves interactive play and exploring. He thrives on puzzle toys and will keep you entertained with his antics.',
      aboutDescription:
        "Hi, I'm Montclair! I'm just a little kitten with a big heart, ready to bring joy and laughter into your life. I love to play with my toys, cuddle up in warm laps, and make new friends. My gentle nature makes me the perfect companion for cozy evenings and playful afternoons. If you're looking for a sweet, friendly, and loving friend, I'm your perfect match! Let's create unforgettable memories together. Adopt me and let's start our adventure!",
    },
    photos: ['/images/bella-1.jpg'],
  },
  {
    slug: 'luna',
    name: 'Luna',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Female',
      age: '1 year',
      size: 'Small',
      color: 'Black & white',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: true,
      goodWithCats: true,
      energyLevel: 'Medium',
      temperament: 'Curious',
      houseTrained: false,
    },
    medicalHistory: { vaccinationsUpToDate: false, spayedOrNeutered: false, microchipped: false },
    adoptionFee: 100,
    photos: ['/images/luna-1.jpg'],
  },
  {
    slug: 'buddy-2',
    name: 'Buddy',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Male',
      age: '4 years',
      size: 'Large',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: false,
      goodWithDogs: true,
      energyLevel: 'Low',
      temperament: 'Calm',
      houseTrained: true,
    },
    medicalHistory: { vaccinationsUpToDate: true, spayedOrNeutered: true, microchipped: true },
    adoptionFee: 110,
    photos: ['/images/buddy-2-1.jpg'],
  },
  {
    slug: 'max-2',
    name: 'Max',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Male',
      age: '6 years',
      size: 'Large',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: false,
      energyLevel: 'Low',
      temperament: 'Gentle',
      houseTrained: true,
    },
    medicalHistory: {
      vaccinationsUpToDate: true,
      spayedOrNeutered: true,
      microchipped: true,
    },
    adoptionFee: 90,
    descriptions: {
      medicalDescription: 'No known medical issues.',
      physicalDescription: 'Curious guy; professional treat inspector.',
      spotlightDescription: 'Montclair is our featured cat of the week — playful and cuddly!',
      behavioralDescription:
        'Loves interactive play and exploring. He thrives on puzzle toys and will keep you entertained with his antics.',
      aboutDescription:
        "Hi, I'm Montclair! I'm just a little kitten with a big heart, ready to bring joy and laughter into your life. I love to play with my toys, cuddle up in warm laps, and make new friends. My gentle nature makes me the perfect companion for cozy evenings and playful afternoons. If you're looking for a sweet, friendly, and loving friend, I'm your perfect match! Let's create unforgettable memories together. Adopt me and let's start our adventure!",
    },
    photos: ['/images/max-2-1.jpg'],
  },
  {
    slug: 'bella-2',
    name: 'Bella',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Female',
      age: '3 years',
      size: 'Medium',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: true,
      energyLevel: 'High',
      temperament: 'Playful',
      houseTrained: true,
    },
    medicalHistory: { vaccinationsUpToDate: true, spayedOrNeutered: true, microchipped: false },
    adoptionFee: 130,
    photos: ['/images/bella-2-1.jpg'],
  },
  {
    slug: 'luna-2',
    name: 'Luna',
    physicalTraits: {
      species: 'Dog',
      breed: 'Mixed Breed',
      sex: 'Female',
      age: '2 years',
      size: 'Small',
    },
    behavioralTraits: {
      mustGoWithAnotherCat: false,
      goodWithKids: true,
      goodWithDogs: true,
      energyLevel: 'Medium',
      temperament: 'Affectionate',
      houseTrained: true,
    },
    medicalHistory: { vaccinationsUpToDate: true, spayedOrNeutered: true, microchipped: true },
    adoptionFee: 125,
    photos: ['/images/luna-2-1.jpg'],
  },
]
